### PR TITLE
Add additional information/references

### PR DESCRIPTION
**Pull request by scoopex**
Enhance and rework networking document

- reworked and enhanced the documentation to make
  it to improve understanding for newbies
- added a reference to the "Cloud Native Data Center Networking" book
- added so references to RFC documents
- added a description which provides to details behind the sharing of ASNs
- remove a outdated reference from 2020 to switch of the deactivation of ipv6
  by setting net.ipv6.conf.swp1.disable_ipv6=0.
  Without checking that, i guessed that this be fixed in the year 2024 :-)

### CODE REVIEW

**Comment by majst01** [comment]
Hi @scoopex 

nice, have you already started with the implementation for your project ?

**Comment by scoopex** [comment]
> Hi @scoopex
> 
> nice, have you already started with the implementation for your project ?

Yes, there are some Openstack Changes and a Netbox integration in progress.

I initially enriched this branch with a few references just for internal discussion with a colleague, but then also made a few extensions based on assumptions (e.g. the diagram).

I think this documentation is very good and informative and it would be great if we could optimize it further.

Would you like to take a look at it and see if it makes sense or do you have a short explanation for the open questions that I have marked with “Q:”. Since my specialization is not in network engineering, I was not able to provide compact or reliable descriptions that are both absolutely correct and easy to understand for newcomers.

**Comment by majst01** [comment]
Maybe we can have a short discussion together with @robertvolkmann.

We also started with netbox but it was far to slow for our expectations and we created https://github.com/metal-stack/go-ipam therefor

**Comment by scoopex** [comment]
> Maybe we can have a short discussion together with @robertvolkmann.
> 
> We also started with netbox but it was far to slow for our expectations and we created https://github.com/metal-stack/go-ipam therefor

For Openstack and Netbox @matofeder is the best person for a discussion.
For the documentation i can do this. 

Which topic should we start with or which topics are interesting for a conferenced exchange?

**Comment by scoopex** [comment]
Hello @majst01 and @robertvolkmann: Today i asked myself - how do you configure K8s MetalLB in bare metal installations with that setup? For Openstack, we just add the Service IPs to the dummy interfaces and the nodes FRR does its job to announce the availability of that address over the BGP peering with the next leaf switches.

For K8s the standard MetalLB mechanism using L2 Broadcasts for leader election cannot work.
Yes, there is the BGP mode for MetalLB, but that seems a bit ineffective and overcomplicated because this spawns an additional FRR instance in my understanding. Is there a more efficient solution? Can you provide a sourcecode/configuration reference?

**Comment by mwindower** [comment]
Hi @scoopex,
we have just one FRR instance running on the bare metal nodes.
This advertises static adresses of the machine s. https://github.com/metal-stack/metal-networker/blob/b22c35f65a2b4f7baf665541c2dceb4484bc2f25/pkg/netconf/tpl/frr.machine.tpl 
Also it allows peering connections (bgp listen range). In the Kubernetes setting metal-lb is used in L3 mode so that it peers with the underlying FRR instance on the metal node.

**Comment by scoopex** [comment]
@robertvolkmann Thanks for the reference to the book. As discussed i eliminated the open questions and tried to put my understanding in the document.

**Comment by robertvolkmann** [comment]
@Gerrit91 @majst01 could you approve and merge?

**Review by majst01 — APPROVED** [review]

**Pull request merged**
