### PR TITLE
Add a diagram which illustrates the network setup

### PR DESCRIPTION
**Pull request by scoopex**
This diagram illustrates the networking setup
Tried to align design a bit to the metal-stack CI.

(i.e. https://docs.metal-stack.io/stable/overview/architecture/)

### CODE REVIEW

**Comment by scoopex** [comment]
Waiting for feedback about the design and the content of the diagram.

**Comment by scoopex** [comment]
> Thanks for the contribution. I think the image is not fully correct, e.g. the tenant firewall should not be connected directly to an exit switch.
> 
> I will take a look into our training material for metal-stack and try to find an illustration of this because I think we have it. > Then it will also have an identical style to most of the other figures that have made for the documentation repository.

@Gerrit91 thanks for the feedback!
Can you give me a reference to the mentioned illustration in the training material (if that is a public resource) or add your diagram to the PR?

**Comment by scoopex** [comment]
> You cannot find them because the training material includes some confidential information. I removed the confidential stuff now and pushed the graphics into the `illustrations` branch: [master...illustrations](https://github.com/metal-stack/docs/compare/master...illustrations)
> 
> You can integrate them into your PR, I was not able to push to your fork.

@Gerrit91 Integrated the proposed changes/additions.

**Review by Gerrit91 — APPROVED** [review]

**Comment by Gerrit91** [comment]
Cool. If you need something else, let us know.

**Pull request merged**
